apiVersion: v1
kind: Namespace
metadata:
  name: awx-mcp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: awx-mcp-config
  namespace: awx-mcp
data:
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8000"
  LOG_LEVEL: "info"
  ENABLE_METRICS: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: awx-mcp-secrets
  namespace: awx-mcp
type: Opaque
stringData:
  admin-token: "change-me-in-production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-mcp-server
  namespace: awx-mcp
  labels:
    app: awx-mcp-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: awx-mcp-server
  template:
    metadata:
      labels:
        app: awx-mcp-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/prometheus-metrics"
    spec:
      containers:
      - name: awx-mcp-server
        image: awx-mcp-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        env:
        - name: SERVER_HOST
          valueFrom:
            configMapKeyRef:
              name: awx-mcp-config
              key: SERVER_HOST
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: awx-mcp-config
              key: SERVER_PORT
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: awx-mcp-secrets
              key: admin-token
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: awx-mcp-server
  namespace: awx-mcp
  labels:
    app: awx-mcp-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: awx-mcp-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-mcp-server
  namespace: awx-mcp
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - awx-mcp.example.com
    secretName: awx-mcp-tls
  rules:
  - host: awx-mcp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: awx-mcp-server
            port:
              name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: awx-mcp-server
  namespace: awx-mcp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: awx-mcp-server
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
